main: net.wytrem.spigot.exmachina.ExMachina
name: ExMachina
version: @version@
api-version: @apiVersion@
description: @description@
author: wytrem
website: @website@
commands:
  exmachina:
    description: Main ExMachina command
    usage: /exmachina <command> <arguments>
    permission: exmachina.use
permissions:
  script.use:
    description: Allows to use /exmachina
    default: op
